# Use the official Node.js image as the base image
FROM node:20

# Create and set the working directory in the container
WORKDIR /app

# Copy the JSON key file into the container
COPY service-account.json /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install project dependencies
RUN npm install

# Copy the rest of the application source code to the container
COPY . .

# Build the Next.js application
RUN npm run build

# Expose the port that the Next.js app will run on
EXPOSE 3000

# Define the command to start your Next.js app
CMD ["npm", "start"]
