name: CI/CD Pipeline

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            backend:
              - 'backend/**'
            frontend:
              - 'frontend/**'

      # Frontend Build and Deploy
      - name: Build and Deploy Frontend
        if: steps.filter.outputs.frontend == 'true'
        run: |
          cd frontend
          npm install
          npm run build
          rm -rf src
          rm -rf node_modules
          gcloud app deploy

      # Backend Build and Deploy
      - name: Build and Deploy Backend
        if: steps.filter.outputs.backend == 'true'
        run: |
          cd backend
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_SERVICE }} .
          gcloud auth configure-docker
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_SERVICE }}
          gcloud run deploy spracto-net-${{ secrets.GCP_SERVICE }} \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_SERVICE }}:latest \
            --region ${{ secrets.GCP_REGION }} \
            --platform managed \
            --allow-unauthenticated
