name: CI/CD new-prod
on:
  push:
    branches:
      - prod
jobs:
  # Job for Backend
  build-and-deploy-app:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud using Workload Identity Federation
        uses: google-github-actions/auth@v1
        with:
          create_credentials_file: true
          workload_identity_provider: "${{ secrets.PROD_WIF_PROVIDER }}"
          service_account: "${{ secrets.PROD_GCP_SA_EMAIL }}"

      - name: Build and Deploy App
        run: |
          cd app
          docker build -t gcr.io/${{ secrets.PROD_GCP_PROJECT_ID }}/${{ secrets.GCP_SERVICE }} .
          gcloud auth configure-docker
          docker push gcr.io/${{ secrets.PROD_GCP_PROJECT_ID }}/${{ secrets.GCP_SERVICE }}
          gcloud run deploy ${{ secrets.GCP_SERVICE }} \
            --image gcr.io/${{ secrets.PROD_GCP_PROJECT_ID }}/${{ secrets.GCP_SERVICE }}:latest \
            --region ${{ secrets.GCP_REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars=DATASTORE_PROJECT_ID=${{ secrets.PROD_GCP_PROJECT_ID }}
